// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package storage

import (
	"time"
)

type MediaLibrary struct {
	ID        int64
	Owner     int64
	CreatedAt time.Time
	Path      string
	Type      string
}

type Profile struct {
	ID       int64
	Username string
	Password string
	Type     int64
}

type Session struct {
	ID           int64
	UserID       int64
	CreatedAt    time.Time
	ExpiresAt    time.Time
	RefreshToken string
}
