// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package storage

import (
	"database/sql"
	"time"
)

type ContentLibrary struct {
	ID             int64
	MediaLibraryID int64
	CreatedAt      time.Time
	FilePath       string
	Extension      string
	Name           string
	Title          string
	Description    sql.NullString
	CoverUrl       sql.NullString
	SeasonNo       sql.NullInt64
	EpisodeNo      sql.NullInt64
	ImdbID         sql.NullInt64
}

type MediaLibrary struct {
	ID          int64
	CreatedAt   time.Time
	Name        string
	Description string
	DevicePath  string
	MediaType   string
	OwnerID     int64
}

type Profile struct {
	ID       int64
	Username string
	Password []byte
	Type     int64
}

type Session struct {
	ID               string
	UserID           int64
	AccessToken      string
	RefreshToken     string
	CreatedAt        time.Time
	AccessExpiresAt  time.Time
	RefreshExpiresAt time.Time
	Device           string
	DeviceName       string
	ClientName       string
	ClientVersion    string
}
